server:
  global:
    scrape_interval: 15s
  service:
    type: LoadBalancer
    port: 9090

  extraScrapeConfigs: |
    - job_name: 'cluster-b-metrics'
      scrape_interval: 15s
      static_configs:
        - targets: ['<CLUSTER-B-IP>:9100']

    - job_name: 'cluster-c-metrics'
      scrape_interval: 15s
      static_configs:
        - targets: ['<CLUSTER-C-IP>:9100']

        server:
  persistentVolume:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
