apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-cluster-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/arunprakash432/end-to-end-multicloud-gitops-project.git'
    targetRevision: HEAD
    path: k8s/helm-charts/python-app
  destination:
    # REMOVE 'server: https://...'
    # ADD 'name' with a fixed logical name
    name: aws-app-cluster
    namespace: default
  # ENABLE AUTO-SYNC
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true