apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-cluster-c
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/arunprakash432/end-to-end-multicloud-gitops-project.git'
    targetRevision: HEAD
    path: k8s/helm-charts/python-app
  destination:
    # -----------------------------------------------------------
    # CRITICAL CHANGE: Use 'name' instead of 'server'
    # This 'azure-app-cluster' matches the name we used in the
    # Jenkinsfile "argocd cluster add" command for Azure.
    # -----------------------------------------------------------
    name: azure-app-cluster
    namespace: default
  
  # Enable Auto-Sync so it deploys immediately
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true